/**
 * Prompts 数据工具函数
 * 从 GitHub CDN 加载提示词数据
 */

// GitHub 仓库 CDN 地址（使用 Statically - 支持大文件）
// 使用 master 分支（仓库的默认分支）
// 或使用 commit SHA 固定版本：7224564a6701d461a9fd87f77ff4d8b8cb393c2f
const GITHUB_CDN = 'https://cdn.statically.io/gh/tkaptop/my-gempix2-prompts-assets/master';

// 备用 CDN（GitHub Raw - 无大小限制）
const BACKUP_CDN = 'https://raw.githubusercontent.com/tkaptop/my-gempix2-prompts-assets/master';

export interface Prompt {
  id: number;
  slug: string;
  title: string;
  locale?: string;
  source?: {
    name: string;
    url: string;
  };
  images: string[];
  prompts: string[];
  examples: string[];
  notes: string[];
  originFile: string;
  // 支持多语言描述或简单字符串（兼容旧数据）
  description: string | {
    en: string;
    zh?: string;
    ja?: string;
    ko?: string;
    es?: string;
    fr?: string;
    de?: string;
    it?: string;
    pt?: string;
    ru?: string;
    ar?: string;
  };
  tags: string[];
  coverImage: string;
  category?: string;
  style?: string;
  model?: string;
  resolution?: string;
  tips?: string[];
  useCases?: string[];
  referenceImages?: string[];
  relatedSlugs?: string[];
  createdBy?: string;
  likes?: number;
  views?: number;
  seoSlug?: string; // SEO 友好的 slug（动态生成）
}

export interface PromptsData {
  generatedAt: string;
  total: number;
  items: Prompt[];
}

/**
 * 生成 SEO 友好的 slug
 * 格式: {tag1}-{tag2}-{tag3}-{id}
 * 例如: photography-interior-portrait-420
 */
const slugifyPart = (value?: string) =>
  value
    ?.toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    ?? '';

export function generateSeoSlug(prompt: Prompt, used?: Set<string>): string {
  const baseParts = [prompt.title, ...(prompt.tags ?? []).slice(0, 2)]
    .map(slugifyPart)
    .filter(Boolean);

  let base = baseParts.join('-');
  if (!base) {
    base = slugifyPart(prompt.title) || `prompt-${prompt.id}`;
  }

  let candidate = base;
  let suffix = 2;
  const registry = used ?? new Set<string>();

  while (registry.has(candidate) || !candidate) {
    candidate = `${base}-${suffix++}`;
  }

  registry.add(candidate);
  return candidate;
}

/**
 * 获取 Prompt 的多语言描述
 * @param prompt - Prompt 对象
 * @param locale - 语言代码（如 'en', 'zh', 'ja'）
 * @returns 对应语言的描述，如果没有则降级到英文或自动生成
 */
export function getLocalizedDescription(prompt: Prompt, locale: string): string {
  const { description } = prompt;

  // 如果 description 是字符串（旧数据格式），直接返回
  if (typeof description === 'string') {
    return description || autoGenerateDescription(prompt, locale);
  }

  // 如果 description 是对象（多语言格式）
  if (description && typeof description === 'object') {
    // 1. 优先返回当前语言
    if (description[locale as keyof typeof description]) {
      return description[locale as keyof typeof description]!;
    }

    // 2. 降级到英文
    if (description.en) {
      return description.en;
    }
  }

  // 3. 如果都没有，自动生成
  return autoGenerateDescription(prompt, locale);
}

/**
 * 自动生成描述（当数据源没有提供时）
 * @param prompt - Prompt 对象
 * @param locale - 语言代码
 * @returns 自动生成的描述
 */
function autoGenerateDescription(prompt: Prompt, locale: string): string {
  const promptText = prompt.prompts?.[0] || '';
  const cleanText = promptText.replace(/\s+/g, ' ').trim();
  const truncated = cleanText.length > 200
    ? cleanText.substring(0, 200) + '...'
    : cleanText;

  const topTags = prompt.tags?.slice(0, 3).join(', ') || '';

  // 根据语言生成模板
  const templates: Record<string, (title: string, text: string, tags: string) => string> = {
    en: (title, text, tags) =>
      `${title} prompt for Nano Banana 2 image generation platform. ${text} Keywords: ${tags}.`,
    zh: (title, text, tags) =>
      `${title} Prompt | 适用于 Nano Banana 2 平台。${text} 关键词：${tags}。`,
    ja: (title, text, tags) =>
      `${title} プロンプト | Nano Banana 2 プラットフォーム用。${text} キーワード：${tags}。`,
    ko: (title, text, tags) =>
      `${title} 프롬프트 | Nano Banana 2 플랫폼용. ${text} 키워드: ${tags}.`,
  };

  const template = templates[locale] || templates.en;
  return template(prompt.title || `Prompt ${prompt.id}`, truncated, topTags);
}

/**
 * 为所有 prompts 添加 seoSlug
 */
function enhancePromptsWithSeoSlug(items: Prompt[]): Prompt[] {
  const used = new Set<string>();

  return items.map(item => {
    const normalizedExisting = item.seoSlug ? slugifyPart(item.seoSlug) : '';

    const seoSlug = normalizedExisting && !used.has(normalizedExisting)
      ? (() => { used.add(normalizedExisting); return normalizedExisting; })()
      : generateSeoSlug(item, used);

    return {
      ...item,
      seoSlug,
    };
  });
}

/**
 * 从 CDN 获取提示词数据
 */
export async function getPrompts(
  options?: {
    signal?: AbortSignal;
  }
): Promise<PromptsData> {
  try {
    // 首先尝试从主 CDN 加载
    const res = await fetch(`${GITHUB_CDN}/data/prompts.json`, {
      next: { revalidate: 3600 }, // 缓存 1 小时，提示词库更新不频繁
      signal: options?.signal,
    });

    if (!res.ok) {
      throw new Error(`HTTP ${res.status}: ${res.statusText}`);
    }

    const data: PromptsData = await res.json();

    // 替换图片 URL 为 CDN 地址，并添加 seoSlug，
    // 同时按 id 降序排序，确保页面永远是 #420, #419, ... 的顺序
    data.items = enhancePromptsWithSeoSlug(
      data.items
        .map(item => ({
          ...item,
          images: item.images.map(img => `${GITHUB_CDN}/${img}`),
          coverImage: `${GITHUB_CDN}/${item.coverImage}`,
        }))
        .sort((a, b) => b.id - a.id)
    );

    return data;
  } catch (error) {
    console.error('Failed to fetch prompts from primary CDN:', error);

    // 尝试备用 CDN
    try {
      const res = await fetch(`${BACKUP_CDN}/data/prompts.json`, {
        next: { revalidate: 3600 }, // 缓存 1 小时
        signal: options?.signal,
      });
      if (!res.ok) {
        throw new Error(`Backup CDN also failed: ${res.status}`);
      }

      const data: PromptsData = await res.json();

      data.items = enhancePromptsWithSeoSlug(
        data.items
          .map(item => ({
            ...item,
            images: item.images.map(img => `${BACKUP_CDN}/${img}`),
            coverImage: `${BACKUP_CDN}/${item.coverImage}`,
          }))
          .sort((a, b) => b.id - a.id)
      );

      return data;
    } catch (backupError) {
      console.error('Backup CDN also failed:', backupError);
      throw new Error('Failed to load prompts data from all CDN sources');
    }
  }
}

/**
 * 获取所有唯一标签
 */
export function getAllTags(data: PromptsData): string[] {
  const tagsSet = new Set<string>();

  data.items.forEach(item => {
    item.tags.forEach(tag => tagsSet.add(tag));
  });

  return Array.from(tagsSet).sort();
}

/**
 * 根据搜索词和标签筛选提示词
 */
export function filterPrompts(
  items: Prompt[],
  searchTerm: string,
  selectedTags: string[]
): Prompt[] {
  return items.filter(item => {
    // 搜索匹配
    const matchSearch = !searchTerm ||
      item.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.id.toString().includes(searchTerm) ||
      item.prompts.some(p => p.toLowerCase().includes(searchTerm.toLowerCase()));

    // 标签匹配
    const matchTags = selectedTags.length === 0 ||
      selectedTags.every(tag => item.tags.includes(tag));

    return matchSearch && matchTags;
  });
}

/**
 * 按 ID 获取单个提示词
 */
export function getPromptById(data: PromptsData, id: number): Prompt | undefined {
  return data.items.find(item => item.id === id);
}

/**
 * 按 slug 获取单个提示词
 * 优先匹配 seoSlug，向后兼容原始 slug
 */
export function getPromptBySlug(data: PromptsData, slug: string): Prompt | undefined {
  const normalizedSlug = slug.toLowerCase();
  return data.items.find(item => {
    const seo = item.seoSlug?.toLowerCase();
    const legacy = item.slug.toLowerCase();
    return seo === normalizedSlug || legacy === normalizedSlug;
  });
}

/**
 * 获取指定 prompt 的上一条和下一条
 * 支持通过 seoSlug 或原始 slug 查找
 */
export function getPromptNeighbors(
  data: PromptsData,
  slug: string
): { prev: Prompt | null; next: Prompt | null } {
  const normalizedSlug = slug.toLowerCase();
  const currentIndex = data.items.findIndex(item => {
    const seo = item.seoSlug?.toLowerCase();
    const legacy = item.slug.toLowerCase();
    return seo === normalizedSlug || legacy === normalizedSlug;
  });

  if (currentIndex === -1) {
    return { prev: null, next: null };
  }

  return {
    prev: currentIndex > 0 ? data.items[currentIndex - 1] : null,
    next: currentIndex < data.items.length - 1 ? data.items[currentIndex + 1] : null,
  };
}

/**
 * 获取相关的提示词
 * 基于标签相似度推荐
 */
export function getRelatedPrompts(
  data: PromptsData,
  currentPrompt: Prompt,
  limit: number = 5
): Prompt[] {
  const normalize = (value?: string) => value?.trim().toLowerCase() || '';
  const canonicalSlug = normalize(currentPrompt.seoSlug || currentPrompt.slug);

  const alreadyAdded = new Set<number>([currentPrompt.id]);
  const results: Prompt[] = [];

  const addPrompt = (prompt?: Prompt) => {
    if (!prompt || alreadyAdded.has(prompt.id)) {
      return;
    }
    alreadyAdded.add(prompt.id);
    results.push(prompt);
  };

  if (currentPrompt.relatedSlugs && currentPrompt.relatedSlugs.length > 0) {
    currentPrompt.relatedSlugs.forEach(slug => {
      const normalizedSlug = normalize(slug);
      if (!normalizedSlug || normalizedSlug === canonicalSlug) {
        return;
      }

      const match = data.items.find(item => {
        const seoSlug = normalize(item.seoSlug);
        const legacySlug = normalize(item.slug);
        return seoSlug === normalizedSlug || legacySlug === normalizedSlug;
      });

      addPrompt(match);
    });
  }

  const primarySlots = Math.min(3, limit);
  if (results.length >= primarySlots) {
    results.splice(primarySlots);
  }

  const scored = data.items
    .filter(item => !alreadyAdded.has(item.id))
    .map(item => {
      const commonTags = item.tags.filter(tag => currentPrompt.tags.includes(tag)).length;
      return { item, score: commonTags };
    })
    .filter(({ score }) => score > 0)
    .sort((a, b) => b.score - a.score);

  for (const { item } of scored) {
    if (results.length >= primarySlots) {
      break;
    }
    addPrompt(item);
  }

  const remainingSlots = Math.max(0, limit - results.length);
  if (remainingSlots === 0) {
    return results.slice(0, limit);
  }

  const pool = data.items.filter(item => !alreadyAdded.has(item.id));
  for (let i = pool.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }

  for (const item of pool) {
    if (results.length >= limit) {
      break;
    }
    addPrompt(item);
  }

  return results.slice(0, limit);
}
